services:
  - type: web
    name: modewallpapers
    env: node
    buildCommand: ./scripts/render-build.sh
    startCommand: npm start
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add your environment variables here:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: your-database-name
      #     property: connectionString
      # - key: SESSION_SECRET
      #   generateValue: true
      # - key: GOOGLE_CLIENT_ID
      #   sync: false
      # - key: GOOGLE_CLIENT_SECRET
      #   sync: false

# If you need a PostgreSQL database, uncomment this:
# databases:
#   - name: modewallpapers-db
#     databaseName: modewallpapers
#     user: modewallpapers
#     plan: free
